name: tutorial-mva-2
channels:
  - defaults
  - conda-forge
dependencies:
  - ipython
  - jupyterlab  # for Jupyter notebooks
  - loadmydata
  - matplotlib
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scipy
  - statsmodels
